[package]
name = "ygod_gtk"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["ygod_lib"]

[dependencies.adw]
package = "libadwaita"
version = "0.2.0-alpha.3"

[dependencies.gtk]
package = "gtk4"
version = "0.4.8"

[dependencies.ygod_lib]
path = "ygod_lib"

[build-dependencies.gtk]
package = "gtk4"
version = "0.4.8"
