[package]
name = "ygo_destiny"
version = "0.1.0"
edition = "2021"
license = "GPLv3 only"

[dependencies.relm4]
package = "relm4"
version = "0.5.0-rc.1"
features = ["libadwaita"]

[dependencies.ygod_core]
path = "ygod_core"

[dependencies]
relm4-components = "0.5.0-rc.1"
relm4-macros = "0.5.0-rc.1"
